#!/bin/bash
# checkusb

# get $PI_USB_DIR from file
source /home/pididsplay/pidisplay.env

dev=none
sudo blkid /dev/sda1
foundusb=$?
if [ "X0" = "X$foundusb" ]; then
  dev=/dev/sda1
else
  sudo blkid /dev/sda
  foundusb=$?
  if [ "X0" = "X$foundusb" ]; then
    dev=/dev/sda
  fi
fi
if [ $dev != "none" ]; then

  echo ""
  echo ""
  echo ""
  echo `date`"  $0  found usb, current video is"
  mkdir -p /home/pidisplay/current
  ls -l /home/pidisplay/current/
  sudo mount $dev /mnt
  echo `date`"  $0  mounted usb, file on usb is:"
  ls -l /mnt/$PI_USB_DIR/*.mp4
  foundfile=$?
  if [ "X0" = "X$foundfile" ]; then
    echo `date`"  $0  found video file"
    mkdir -p /home/pidisplay/new
    echo "clear any files in /home/pidisplay/new"
    ls -l /home/pidisplay/new/*
    newnotempty=$?
    if [ "X0" = "X$newnotempty" ]; then
      rm /home/pidisplay/new/*
    fi
    rsync -t --progress /mnt/$PI_USB_DIR/*.mp4 /home/pidisplay/new
    echo `date`"  $0  copied file, new video is"
    ls -l /home/pidisplay/new/
    # skip testing
    echo "skip testing, keep the new video"
    mkdir -p /home/pidisplay/old
    echo "clear any files in /home/pidisplay/old"
    ls -l /home/pidisplay/old/*
    oldnotempty=$?
    if [ "X0" = "X$oldnotempty" ]; then
      rm /home/pidisplay/old/*
    fi
    mv /home/pidisplay/current/* /home/pidisplay/old/
    mv /home/pidisplay/new/* /home/pidisplay/current/
    echo "moved new file into place"
    ls -l /home/pidisplay/current/
  else
    echo "no file found on usb"
  fi
  sudo umount /mnt
  echo `date`"  $0  unmounted usb"
fi

