#!/bin/bash
# displayloop
# loop forever

# avoid a gap by using --loop
# but then cannot break by inserting usb

/root/bin/play --loop /root/current/*.mp4

exit 0


foundusb=0
while [ $foundusb ]
do
  /root/bin/play /root/current/*.mp4
  blkid /dev/sda1
  foundusb=$?
done
echo "found usb, stop displayloop"
