#!/bin/sh -e
# start
# part of pidisplay
# call this from rc.local or another startup method

/root/bin/checkusb
# for debugging, uncomment the output redirect
/root/bin/displayloop   ## >> /var/log/displayloop.log 2>&1 < /dev/null &
# with --loop, clear console is not needed
#/root/bin/clearconsole 5 &

exit 0
